Feature forms
DejazmachMolla/re-former pull request #1
Opened 2020-09-21 21:47 UTC by DejazmachMolla

- The project should enable adding and editing users
- The project should specify correct input types
- Forms inputs should be labled
- The project should provide error information on the user edit page
- The code should be linted

2020-09-21 22:19 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello,

Thank you for the job done so far.
Just few things to change. Kindly read the comments left below, please and update your code.

Once done, submit a new code review request

Thanks

Mael FOSSO

2020-09-21 22:19 UTC, maelfosso commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path
If it's OK redirect to `edit_user_path`

2020-09-21 22:19 UTC, maelfosso commented on app/views/users/new.html.erb
> +<%# <form action="/users" method="post" accept-charset="UTF-8">
It's preferable to use Rails helpers `users_path`

2020-09-21 22:19 UTC, maelfosso commented on app/views/users/new.html.erb
> +<%#= form_tag("/users", method: "post") do %>
It's preferable to use Rails helpers `users_path`

2020-09-22 03:50 UTC, MarioDena approved these changes
Hello Great work implementing the requested changes!

Project approved! 🎖️ 

Cheers!

2020-09-22 11:56 UTC, merged